[package]
name = "ringr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ringr"
path = "src/main.rs"

[dependencies]
rppal = "0.17.1"
#soloud = { version = "1", default-features = false, features = ["alsa"] }
soloud = { version = "1" }